// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7fsvhFNgO3S8rGG9aiKopcD8LA5aw0Vc',
    appId: '1:284172182295:web:2f7d00e5fb2b568b8ecd52',
    messagingSenderId: '284172182295',
    projectId: 'nadi-staff-c8ce1',
    authDomain: 'nadi-staff-c8ce1.firebaseapp.com',
    storageBucket: 'nadi-staff-c8ce1.firebasestorage.app',
    measurementId: 'G-PFM71BQFYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6PW2_GN8tNcDs6Uju88BQdqhzOp2n-7g',
    appId: '1:284172182295:android:e48e866f3e4c24b58ecd52',
    messagingSenderId: '284172182295',
    projectId: 'nadi-staff-c8ce1',
    storageBucket: 'nadi-staff-c8ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErmuEPTAj-Sv86tRkBWZsthjcHygOobg',
    appId: '1:284172182295:ios:84c5e680909dc87b8ecd52',
    messagingSenderId: '284172182295',
    projectId: 'nadi-staff-c8ce1',
    storageBucket: 'nadi-staff-c8ce1.firebasestorage.app',
    iosBundleId: 'com.hgtech.nadistaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErmuEPTAj-Sv86tRkBWZsthjcHygOobg',
    appId: '1:284172182295:ios:84c5e680909dc87b8ecd52',
    messagingSenderId: '284172182295',
    projectId: 'nadi-staff-c8ce1',
    storageBucket: 'nadi-staff-c8ce1.firebasestorage.app',
    iosBundleId: 'com.hgtech.nadistaff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7fsvhFNgO3S8rGG9aiKopcD8LA5aw0Vc',
    appId: '1:284172182295:web:67fc263b37042bf08ecd52',
    messagingSenderId: '284172182295',
    projectId: 'nadi-staff-c8ce1',
    authDomain: 'nadi-staff-c8ce1.firebaseapp.com',
    storageBucket: 'nadi-staff-c8ce1.firebasestorage.app',
    measurementId: 'G-3V2E55950W',
  );
}
